services:
  prod:
    image: ghcr.io/winfriedjacobs/2026-rmr-pdfreports:feature-restart-2025
    container_name: rmr-pdf-reports-prod
    restart: no # unless-stopped

    volumes:
      - ./pdfs:/app/pdfs:z  # :z for SELinux systems

    environment:
      DB_TYPE: oracle
      DB_CONNECT_STRING: fedora-w540/FREEPDB1
      DB_USER: system
      DB_PASSWORD: DeinSicheresPasswort123



  dev:
    image: ghcr.io/winfriedjacobs/2026-rmr-pdfreports:feature-restart-2025
    container_name: rmr-pdf-reports-dev
    # restart: no # unless-stopped

    volumes:
      - ./pdfs:/app/pdfs:z  # :z for SELinux systems
      - ./sdm_backend_4a.sqlite3:/app/sdm_backend_4a.sqlite3:z  # :z for SELinux systems

    environment:
      DB_TYPE: sqlite
      DB_PATH: sdm_backend_4a.sqlite3


    # Optional: Map ports if the app has a web interface (e.g., Host 8080 to Container 80)
    # ports:
    #   - "8080:80"
    # Optional: Add environment variables if the image requires them
    # environment:
    #   - NODE_ENV=production


